simulation:
  nrep: 100
  nref: ?params.model["n_ref"]
  ntgt: ?params.model["n_tgt"]
  ref_id: ?params.ref_id
  tgt_id: ?params.tgt_id
  src_id: ?params.src_id
  seq_len: 50000
  mut_rate: ?params.model["mu"]
  rec_rate: ?params.model["rho"]
  ploidy: 2
  is_phased: True
  output_dir: ?params.output_dir
  output_prefix: ?params.train_output_prefix
  nfeature: ?params.nfeature
  feature_config_file: "config/ArchIE.features.yaml"
  intro_prop: 0.7
  non_intro_prop: 0.3
  is_shuffled: False
  force_balanced: False
  nprocess: ?params.nprocess
  seed: ?params.seedmsprime

preprocess:
  vcf_file: ?params.vcf_file
  chr_name: "1"
  ref_ind_file: ?params.ref_ind_file
  tgt_ind_file: ?params.tgt_ind_file
  win_len: 50000
  win_step: 10000
  is_phased: True
  feature_config_file: "config/ArchIE.features.yaml"
  output_dir: ?params.output_dir
  output_prefix: ?params.infer_output_prefix
  nprocess: ?params.nprocess
  ploidy: 2

model:
  name: "logistic_regression"
  params:
    solver: "newton-cg"
    penalty: ~
    max_iter: 10000
    random_state: 12345
