simulation:
  nrep: 100
  nref: 5
  ntgt: 5
  ref_id: "Reference"
  tgt_id: "Target"
  src_id: "Source"
  seq_len: 50000
  mut_rate: 1.2e-8
  rec_rate: 1e-8
  ploidy: 2
  is_phased: True
  output_prefix: "gaishi.lr"
  output_dir: "results/gaishi/training"
  nfeature: 100
  feature_config_file: "config/ArchIE.features.yaml"
  intro_prop: 0.7
  non_intro_prop: 0.3
  is_shuffled: False
  force_balanced: False
  nprocess: 2
  seed: 12345

model:
  name: "logistic_regression"
  params:
    solver: "newton-cg"
    penalty: ~
    max_iter: 10000
    random_state: 12345
